# Generated by Django 6.0 on 2025-12-17 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_user_close_friend_delete_post_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=20, verbose_name='گذرواژه')),
                ('birthdate', models.DateField(null=True, verbose_name='تاریخ تولد')),
                ('bio', models.TextField(null=True, verbose_name='بیوگرافی')),
                ('city', models.CharField(choices=[('tehran', 'تهران'), ('isfahan', 'اصفهان')], default='isfahan', max_length=20, verbose_name='شهر')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('close_friend', models.ManyToManyField(blank=True, null=True, to='core.user', verbose_name='دوستان صمیمی')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('visible', models.BooleanField(default=False, verbose_name='قابل مشاهده')),
                ('show_to', models.CharField(choices=[('nobody', 'هیجکس'), ('closefriends', 'دوستان صمیمی'), ('all', 'همه')], default='nobody', max_length=20, verbose_name='نمایش برای')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('category', models.CharField(choices=[('social', 'اجتماعی'), ('sport', 'ورزشی')], max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست',
            },
        ),
    ]
